import { z } from "zod";

const titleSchema = z.object({
  en: z.string().min(1),
  bn: z.string().optional(),
});

const classificationSchema = z.object({
  id: z.string(),
  title: titleSchema,
  slug: z.string(),
  image: z.string().optional(),
});

export const createProductSchema = z.object({
  title: titleSchema,
  img: z.array(z.string()).min(1),
  regularPrice: z.number().min(0),
  salePrice: z.number().min(0),
  isAffiliate: z.boolean().optional(),
  affCommAmount: z.number().min(0).optional(),
  seller: z.string().optional(),
  type: classificationSchema,
  category: classificationSchema,
  subcategory: classificationSchema,
  brand: classificationSchema.optional(),
  productModel: classificationSchema.optional(),
  
  fashionInfo: z.object({
    gender: z.string().optional(),
    size: z.string().optional(),
    color: z.string().optional(),
    material: z.string().optional(),
    fit: z.string().optional(),
    pattern: z.string().optional(),
    sleeve: z.string().optional(),
    neckline: z.string().optional(),
    occasion: z.string().optional(),
    season: z.string().optional(),
    careInstructions: z.string().optional(),
    countryOfOrigin: z.string().optional(),
  }).optional(),
  
  computerAccessoriesInfo: z.object({
    processor: z.string().optional(),
    ram: z.string().optional(),
    storage: z.string().optional(),
    graphics: z.string().optional(),
    display: z.string().optional(),
    os: z.string().optional(),
    screenResolution: z.string().optional(),
    refreshRate: z.string().optional(),
    ports: z.string().optional(),
    weight: z.string().optional(),
    batteryLife: z.string().optional(),
    warranty: z.string().optional(),
  }).optional(),
  
  automobileInfo: z.object({
    engineCapacity: z.string().optional(),
    fuelType: z.string().optional(),
    transmission: z.string().optional(),
    mileage: z.string().optional(),
    year: z.number().optional(),
    condition: z.string().optional(),
    color: z.string().optional(),
    seatingCapacity: z.number().optional(),
    topSpeed: z.string().optional(),
    torque: z.string().optional(),
    brakeType: z.string().optional(),
    warranty: z.string().optional(),
  }).optional(),
  
  furnitureInfo: z.object({
    material: z.string().optional(),
    dimensions: z.string().optional(),
    weight: z.string().optional(),
    color: z.string().optional(),
    assembly: z.string().optional(),
    style: z.string().optional(),
    finish: z.string().optional(),
    seatingCapacity: z.number().optional(),
    weightCapacity: z.string().optional(),
    warranty: z.string().optional(),
    careInstructions: z.string().optional(),
  }).optional(),
  
  booksStationeryInfo: z.object({
    author: z.string().optional(),
    publisher: z.string().optional(),
    isbn: z.string().optional(),
    pages: z.number().optional(),
    language: z.string().optional(),
    edition: z.string().optional(),
    publicationDate: z.string().optional(),
    binding: z.string().optional(),
    dimensions: z.string().optional(),
    weight: z.string().optional(),
    genre: z.string().optional(),
  }).optional(),
  
  electronicsInfo: z.object({
    screenSize: z.string().optional(),
    battery: z.string().optional(),
    camera: z.string().optional(),
    storage: z.string().optional(),
    ram: z.string().optional(),
    connectivity: z.string().optional(),
    processor: z.string().optional(),
    os: z.string().optional(),
    simType: z.string().optional(),
    networkType: z.string().optional(),
    weight: z.string().optional(),
    warranty: z.string().optional(),
  }).optional(),
  
  homeAppliancesInfo: z.object({
    capacity: z.string().optional(),
    powerConsumption: z.string().optional(),
    voltage: z.string().optional(),
    warranty: z.string().optional(),
    energyRating: z.string().optional(),
    dimensions: z.string().optional(),
    weight: z.string().optional(),
    color: z.string().optional(),
    material: z.string().optional(),
    features: z.string().optional(),
    noiseLevel: z.string().optional(),
  }).optional(),
  
  sportsFitnessInfo: z.object({
    weight: z.string().optional(),
    dimensions: z.string().optional(),
    maxLoad: z.string().optional(),
    material: z.string().optional(),
    features: z.string().optional(),
    color: z.string().optional(),
    adjustable: z.boolean().optional(),
    foldable: z.boolean().optional(),
    warranty: z.string().optional(),
    targetArea: z.string().optional(),
    difficulty: z.string().optional(),
  }).optional(),
  
  beautyPersonalCareInfo: z.object({
    skinType: z.string().optional(),
    volume: z.string().optional(),
    ingredients: z.string().optional(),
    scent: z.string().optional(),
    expiry: z.string().optional(),
    brand: z.string().optional(),
    usage: z.string().optional(),
    benefits: z.string().optional(),
    suitableFor: z.string().optional(),
    certifications: z.string().optional(),
    countryOfOrigin: z.string().optional(),
  }).optional(),
  
  toysGamesInfo: z.object({
    ageRange: z.string().optional(),
    material: z.string().optional(),
    dimensions: z.string().optional(),
    batteryRequired: z.boolean().optional(),
    safetyStandard: z.string().optional(),
    weight: z.string().optional(),
    color: z.string().optional(),
    numberOfPlayers: z.string().optional(),
    skillDevelopment: z.string().optional(),
    warranty: z.string().optional(),
  }).optional(),
  
  jewelryWatchesInfo: z.object({
    material: z.string().optional(),
    dialSize: z.string().optional(),
    strapMaterial: z.string().optional(),
    waterResistance: z.string().optional(),
    warranty: z.string().optional(),
    movement: z.string().optional(),
    displayType: z.string().optional(),
    features: z.string().optional(),
    weight: z.string().optional(),
    color: z.string().optional(),
    gender: z.string().optional(),
  }).optional(),
  
  foodBeveragesInfo: z.object({
    weight: z.string().optional(),
    ingredients: z.string().optional(),
    nutritionInfo: z.string().optional(),
    expiryDate: z.string().optional(),
    storage: z.string().optional(),
    flavor: z.string().optional(),
    brand: z.string().optional(),
    countryOfOrigin: z.string().optional(),
    servingSize: z.string().optional(),
    allergenInfo: z.string().optional(),
    certifications: z.string().optional(),
  }).optional(),
  
  healthWellnessInfo: z.object({
    dosage: z.string().optional(),
    ingredients: z.string().optional(),
    usage: z.string().optional(),
    sideEffects: z.string().optional(),
    expiryDate: z.string().optional(),
    form: z.string().optional(),
    quantity: z.string().optional(),
    benefits: z.string().optional(),
    warnings: z.string().optional(),
    storage: z.string().optional(),
    certifications: z.string().optional(),
  }).optional(),
  
  petSuppliesInfo: z.object({
    petType: z.string().optional(),
    weight: z.string().optional(),
    ingredients: z.string().optional(),
    ageGroup: z.string().optional(),
    expiryDate: z.string().optional(),
    flavor: z.string().optional(),
    brand: z.string().optional(),
    nutritionInfo: z.string().optional(),
    feedingGuidelines: z.string().optional(),
    storage: z.string().optional(),
    certifications: z.string().optional(),
  }).optional(),
  
  musicalInstrumentsInfo: z.object({
    instrumentType: z.string().optional(),
    material: z.string().optional(),
    strings: z.number().optional(),
    finish: z.string().optional(),
    accessories: z.string().optional(),
    color: z.string().optional(),
    weight: z.string().optional(),
    dimensions: z.string().optional(),
    skillLevel: z.string().optional(),
    warranty: z.string().optional(),
    countryOfOrigin: z.string().optional(),
  }).optional(),
});

export const updateProductSchema = createProductSchema.partial();
